version: '3.6'

services:
  db:
    image: mysql:latest
    volumes:
      - ./db-volume:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: cabin
      MYSQL_USER: sklep
      MYSQL_PASSWORD: sklep

  my-sql-adminer:
    image: adminer
    ports:
      - 8087:8080

  # mysql -h 127.0.0.1 -u root -P 3306 -p mysql         rootpw