version: '3.7'

services:
  mysql:
    #image: mysql:8.0.16 - TODO add support to newer version if required
    image: mysql:5.7.17
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d/
      - ./storage:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password

  mysql-admin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8087:80"
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql